FROM ruby:3.0.0

# throw errors if Gemfile has been modified since Gemfile.lock

WORKDIR /usr/src/app

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

CMD ["rails", "server", "-b", "0.0.0.0", "&&"]