# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app

  app:
    build:
      context: ./
      dockerfile: dockerfile
    
    command: bash -c "rm -f tmp/pids/server.pid && rails db:create db:migrate db:seed && bundle exec rails server -p 3000 -b '0.0.0.0'" 
    depends_on:
      - db
    ports:
      - '3000:3000'
    links:
      - db
    volumes:
      - '.:/app'
    networks:
      - app

  nginx:
    build:
      context: docker/web/
      dockerfile: dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - app

volumes:
  postgres_data:

networks:
  app:
    driver: bridge